---
title: "Day 4 Interactive Session"
format: html
editor: visual
---

## Functions

a function that doubles a value

```{r}
double_value <- function(my_dollars) {
  print(2 * my_dollars)
}
#nothing returned yet because this is just making the function
```

```{r}
double_value(my_dollars = 10.13)
```

```{r}
#you don't need to specify the varaible
double_value(10.13)
```

```{r}
monthly_income <- c(42.50, 61.75, 89.50)
double_value(monthly_income)
```

Making a function that returns an awesome restaurant name given a cool animal and your favorite food.

```{r}
#pasting string and printing it
name_restaurant <- function(animal, food) {
  print(paste0(animal, food))
}

name_restaurant(animal="hawk", food= "pizza")
```

Given temperature in degrees Fahrenheit, write a function that coverts it to Celsius.

```{r}
temp_celsius <- function(temp_F) {
  print((temp_F -32)*(5/9))
}

temp_celsius(temp_F = 32)
```

Make a function that given inputs of age and hometown returns i am \_\_\_ and i'm from \_\_\_\_

```{r}
introduction_fn <- function(age, hometown){
  print(paste0("I am ",age," years old, and I'm from ", hometown, "."))
}

introduction_fn(age= 22, hometown = "Buena Park")
```

```{r}
double_value2 <- function(dollars){
  dollars * 2
}
double_value2(dollars = 10)
```
